### ISSUE TITLE
Double login

### ISSUE THREAD

**Issue by BJWielink** [thedaneeffect/RuneScape-317#5]
Not sure if you're aware of it, but when I use the Hyperion source with this client and login once, I see another character called Invalid Name. This doesn't happen with the original deob.

![image](https://user-images.githubusercontent.com/23128923/116709037-94d1c800-a9d0-11eb-9855-da1ded0020c0.png)

Moreover the character that is in the range doesn't compile (for me atlesat):

`private static final int RANGE = ' ' + '\243'; // least significant char + most significant char (in terms of value)`

For this reason I changed it to the decimal value \243

**Comment by thedaneeffect** [comment]
Are you positive that invalid character isn't there due to attempting to login without a username?

That character in RANGE requires that you use UTF-8 encoding, but I'll change it to its unicode escaped format. \243 is an octal escape by the way.
